### ISSUE TITLE
Code Publish

### ISSUE THREAD

**Issue by Anton123567** [Vujas-Eteph/LazyXMem#1]
Hi,
I really liked your paper. When are you planning on publishing the code?

**Comment by Vujas-Eteph** [comment]
Hi,
I'm waiting for the paper to be accepted, as most of the refactoring is done and tested. I'll update the issue when the code is available so you get a notification.
Cheers :)

**Comment by Vujas-Eteph** [comment]
Hi Anton,
I've started releasing the code. It's still a mess IMO, but hopefully you can get something out of it 🤗
If you have any problems, feel free to open an issue (I'm also open to pull requests).
